
from time import time


RECORD_VIDEO = False
START_TIME = time()

CANVAS_WIDTH = 600
CANVAS_HEIGHT = 600
CELL_SIZE = 12       

WORLD_WIDTH = int(CANVAS_WIDTH / CELL_SIZE)
WORLD_HEIGHT = int(CANVAS_HEIGHT / CELL_SIZE)

NUM_WALKERS = 800

BACKGROUND_COLOUR = 0
