
from time import time



SHOW_TEXT = False

RECORD_VIDEO = False
START_TIME = time()

SKETCH_WIDTH = 800
SKETCH_HEIGHT = 800
CELL_SIZE = 16       

WORLD_WIDTH = int(SKETCH_WIDTH / CELL_SIZE)
WORLD_HEIGHT = int(SKETCH_HEIGHT / CELL_SIZE)

NUM_WALKERS = 1000

BACKGROUND_COLOUR = 0