
from time import time



SHOW_TEXT = False

RECORD_VIDEO = True
START_TIME = time()

CANVAS_WIDTH = 800
CANVAS_HEIGHT = 800
CELL_SIZE = 16       

WORLD_WIDTH = int(CANVAS_WIDTH / CELL_SIZE)
WORLD_HEIGHT = int(CANVAS_HEIGHT / CELL_SIZE)

NUM_WALKERS = 1000

BACKGROUND_COLOUR = 0